// TRADUCCIONES ADICIONALES PARA CURSOS DE AUTOESTIMA Y COMUNICACIÓN
// Este archivo extiende el objeto translations en funciones.js

// Esperar a que translations esté disponible
if (typeof translations !== 'undefined') {
    // Extender traducciones en español
    Object.assign(translations.es, {
    // CURSO AUTOESTIMA - SELF-ESTEEM
    courseSelfEsteemTitlePage: "Autoestima y Amor Propio | Vivir en el Amor",
    courseSelfEsteemTitle: "Autoestima y Amor Propio | Vivir en el Amor",
    courseSelfEsteemHeroTitle: "Autoestima y Amor Propio: El Camino hacia tu Mejor Versión",
    courseSelfEsteemHeroSubtitle: "Reconstruye tu confianza, ámate incondicionalmente y crea la vida que mereces desde el amor propio",
    courseSelfEsteemModules: "6 módulos completos",
    courseSelfEsteemDuration: "4 semanas intensivas",
    courseSelfEsteemAccess: "Acceso de por vida",
    courseSelfEsteemCertificate: "Certificado incluido",
    courseSelfEsteemWorkbook: "Workbook descargable",
    courseSelfEsteemDescTitle: "Sobre este curso",
    courseSelfEsteemDesc1: "¿Te sientes atrapada en patrones de autocrítica constante? ¿Dudas de tu valor y permites que otros crucen tus límites? Es hora de transformar tu relación contigo misma y construir una autoestima inquebrantable que te sostenga en cada área de tu vida.",
    courseSelfEsteemDesc2: "En este programa de 6 módulos, explorarás las raíces de tu autoestima, identificarás patrones autodestructivos, reconstruirás tu autoimagen y aprenderás prácticas de amor propio que transformarán tu vida. Este no es un curso más de motivación: es un proceso profundo de sanación y empoderamiento personal.",
    courseSelfEsteemBenefitsTitle: "¿Qué lograrás?",
    courseSelfEsteemBenefit1: "Comprender las bases psicológicas de la autoestima y cómo fortalecerla",
    courseSelfEsteemBenefit2: "Identificar y transformar patrones de autosabotaje y autocrítica",
    courseSelfEsteemBenefit3: "Desarrollar una autoimagen positiva y realista",
    courseSelfEsteemBenefit4: "Practicar amor propio auténtico en tu día a día",
    courseSelfEsteemBenefit5: "Crear rutinas de autocuidado que nutran tu bienestar integral",
    courseSelfEsteemBenefit6: "Mantener tu autoestima elevada incluso en momentos difíciles",
    courseSelfEsteemCurriculumTitle: "Contenido del curso",
    courseSelfEsteemModule1: "Las Bases de la Autoestima",
    courseSelfEsteemModule1Duration: "4 lecciones",
    courseSelfEsteemModule1L1: "Qué es la autoestima y por qué es fundamental",
    courseSelfEsteemModule1L2: "Los 4 pilares de la autoestima saludable",
    courseSelfEsteemModule1L3: "Evaluación personal: ¿Dónde está tu autoestima ahora?",
    courseSelfEsteemModule1L4: "Ejercicio: Tu mapa de autoestima",
    courseSelfEsteemModule2: "Identificar Patrones Autodestructivos",
    courseSelfEsteemModule2Duration: "3 lecciones",
    courseSelfEsteemModule2L1: "Reconocer el diálogo interno negativo",
    courseSelfEsteemModule2L2: "Patrones de autosabotaje más comunes",
    courseSelfEsteemModule2L3: "De dónde vienen tus creencias limitantes",
    courseSelfEsteemModule3: "Reconstruir tu Autoimagen",
    courseSelfEsteemModule3Duration: "4 lecciones",
    courseSelfEsteemModule3L1: "Desafiar las creencias limitantes",
    courseSelfEsteemModule3L2: "Crear afirmaciones poderosas que funcionen",
    courseSelfEsteemModule3L3: "Técnica del espejo: Amarte a ti misma",
    courseSelfEsteemModule3L4: "Celebrar tus fortalezas y logros",
    courseSelfEsteemModule4: "Amor Propio en la Práctica",
    courseSelfEsteemModule4Duration: "3 lecciones",
    courseSelfEsteemModule4L1: "Qué es el amor propio real (no egoísmo)",
    courseSelfEsteemModule4L2: "Auto-compasión: Tratarte con gentileza",
    courseSelfEsteemModule4L3: "Perdonarte a ti misma",
    courseSelfEsteemModule5: "Autocuidado Integral",
    courseSelfEsteemModule5Duration: "3 lecciones",
    courseSelfEsteemModule5L1: "Crear tu rutina de autocuidado personalizada",
    courseSelfEsteemModule5L2: "Autocuidado físico, emocional y espiritual",
    courseSelfEsteemModule5L3: "Decir NO sin culpa",
    courseSelfEsteemModule6: "Mantener tu Autoestima Alta",
    courseSelfEsteemModule6Duration: "4 lecciones",
    courseSelfEsteemModule6L1: "Proteger tu autoestima de ataques externos",
    courseSelfEsteemModule6L2: "Rodearte de personas que te eleven",
    courseSelfEsteemModule6L3: "Plan de mantenimiento a largo plazo",
    courseSelfEsteemModule6L4: "Celebración final y compromiso contigo misma",
    courseSelfEsteemInstructorTitle: "Tu instructora",
    courseSelfEsteemInstructorRole: "Coach de Autoestima y Desarrollo Personal",
    courseSelfEsteemInstructorBio: "Michelle ha ayudado a más de 800 mujeres a reconstruir su autoestima y descubrir su valor. Su enfoque combina técnicas de psicología positiva, coaching transformacional y prácticas espirituales.",
    courseSelfEsteemPriceHeader: "Inscríbete ahora",
    courseSelfEsteemPriceSubtext: "Pago único - Acceso de por vida",
    courseSelfEsteemCTA: "Comenzar Ahora",
    courseSelfEsteemFeature1: "Acceso ilimitado de por vida",
    courseSelfEsteemFeature2: "Disponible en todos tus dispositivos",
    courseSelfEsteemFeature3: "Certificado de finalización",
    courseSelfEsteemFeature4: "Workbook descargable con ejercicios",
    courseSelfEsteemGuaranteeTitle: "Garantía de 30 días",
    courseSelfEsteemGuaranteeText: "Si no estás satisfecha, te devolvemos tu dinero sin preguntas.",
    courseSelfEsteemStat1: "estudiantes transformadas",
    courseSelfEsteemStat2: "valoración promedio",
    courseSelfEsteemStat3: "tasa de finalización",
    courseSelfEsteemTestimonialsTitle: "Lo que dicen nuestras estudiantes",
    courseSelfEsteemTestimonial1: "\"Este curso me cambió la vida. Aprendí a amarme y respetarme de verdad. Hoy me siento segura y feliz conmigo misma.\"",
    courseSelfEsteemTestimonial1Role: "Desarrollo personal",
    courseSelfEsteemTestimonial2: "\"Las técnicas de auto-compasión fueron revolucionarias. Dejé de ser mi peor crítica y me convertí en mi mejor aliada.\"",
    courseSelfEsteemTestimonial2Role: "Coaching individual",
    courseSelfEsteemTestimonial3: "\"Finalmente entendí que merezco amor y respeto. Este curso fue el inicio de mi verdadera transformación.\"",
    courseSelfEsteemTestimonial3Role: "Curso online",
    
    // CURSO COMUNICACIÓN - COMMUNICATION
    courseCommunicationTitlePage: "Comunicación en Pareja | Vivir en el Amor",
    courseCommunicationTitle: "Comunicación en Pareja | Vivir en el Amor",
    courseCommunicationHeroTitle: "Comunicación en Pareja: Conexión Profunda a Través de las Palabras",
    courseCommunicationHeroSubtitle: "Domina el arte de la comunicación efectiva y transforma tus relaciones creando conexiones profundas y duraderas",
    courseCommunicationModules: "7 módulos completos",
    courseCommunicationDuration: "5 semanas de transformación",
    courseCommunicationAccess: "Acceso de por vida",
    courseCommunicationCommunity: "Grupo de práctica exclusivo",
    courseCommunicationCertificate: "Certificado incluido",
    courseCommunicationSupport: "Soporte directo de Michelle",
    courseCommunicationDescTitle: "Sobre este curso",
    courseCommunicationDesc1: "¿Sientes que no te escuchan? ¿Las discusiones siempre terminan mal? Este curso te enseñará a comunicarte de manera efectiva, empática y transformadora en tu relación.",
    courseCommunicationDesc2: "A través de 7 módulos prácticos, aprenderás las técnicas más poderosas de comunicación no violenta, escucha activa y resolución de conflictos para crear conexiones profundas y duraderas.",
    courseCommunicationBenefitsTitle: "¿Qué lograrás?",
    courseCommunicationBenefit1: "Dominar la comunicación no violenta y empática",
    courseCommunicationBenefit2: "Expresar necesidades sin atacar ni herir",
    courseCommunicationBenefit3: "Desarrollar escucha activa y profunda",
    courseCommunicationBenefit4: "Transformar conflictos en oportunidades de crecimiento",
    courseCommunicationBenefit5: "Interpretar y usar el lenguaje corporal efectivamente",
    courseCommunicationBenefit6: "Crear rituales de comunicación diaria con tu pareja",
    courseCommunicationBenefit7: "Crear un plan de comunicación personalizado para tu relación",
    courseCommunicationCurriculumTitle: "Contenido del curso",
    courseCommunicationModule1: "Fundamentos de la Comunicación Efectiva",
    courseCommunicationModule1Duration: "3 lecciones",
    courseCommunicationModule1L1: "Por qué falla la comunicación en las parejas",
    courseCommunicationModule1L2: "Los 4 pilares de la comunicación consciente",
    courseCommunicationModule1L3: "Evaluación: ¿Cómo te comunicas ahora?",
    courseCommunicationModule2: "Barreras de Comunicación",
    courseCommunicationModule2Duration: "4 lecciones",
    courseCommunicationModule2L1: "Los 4 jinetes del apocalipsis en la comunicación",
    courseCommunicationModule2L2: "Crítica vs. queja: La diferencia crucial",
    courseCommunicationModule2L3: "Defensividad: Cómo superarla",
    courseCommunicationModule2L4: "Ejercicio: Identificar tus barreras",
    courseCommunicationModule3: "Escucha Activa y Empática",
    courseCommunicationModule3Duration: "3 lecciones",
    courseCommunicationModule3L1: "Qué es escuchar de verdad",
    courseCommunicationModule3L2: "Técnicas de validación emocional",
    courseCommunicationModule3L3: "Práctica: Ejercicios de escucha profunda",
    courseCommunicationModule4: "Expresar Necesidades Sin Atacar",
    courseCommunicationModule4Duration: "4 lecciones",
    courseCommunicationModule4L1: "La fórmula de la comunicación no violenta",
    courseCommunicationModule4L2: "Usar mensajes 'Yo' en lugar de 'Tú'",
    courseCommunicationModule4L3: "Expresar emociones sin culpar",
    courseCommunicationModule4L4: "Ejercicio: Reescribir conversaciones difíciles",
    courseCommunicationModule5: "Lenguaje Corporal y Comunicación No Verbal",
    courseCommunicationModule5Duration: "3 lecciones",
    courseCommunicationModule5L1: "El 93% que no son palabras",
    courseCommunicationModule5L2: "Leer el lenguaje corporal de tu pareja",
    courseCommunicationModule5L3: "Alinear tu comunicación verbal y no verbal",
    courseCommunicationModule6: "Gestionar Conversaciones Difíciles",
    courseCommunicationModule6Duration: "3 lecciones",
    courseCommunicationModule6L1: "Prepararte para conversaciones difíciles",
    courseCommunicationModule6L2: "Técnica del tiempo fuera consciente",
    courseCommunicationModule6L3: "Llegar a acuerdos ganar-ganar",
    courseCommunicationModule7: "Plan de Comunicación para Parejas",
    courseCommunicationModule7Duration: "3 lecciones",
    courseCommunicationModule7L1: "Crear rituales de comunicación diaria",
    courseCommunicationModule7L2: "Reuniones de pareja: Cómo y cuándo",
    courseCommunicationModule7L3: "Tu plan de acción personalizado",
    courseCommunicationInstructorTitle: "Tu instructora",
    courseCommunicationInstructorRole: "Terapeuta de Parejas y Experta en Comunicación",
    courseCommunicationInstructorBio: "Michelle ha facilitado más de 5,000 sesiones de terapia de pareja, especializándose en comunicación efectiva. Su método ha ayudado a cientos de parejas a reconectar y fortalecer su amor.",
    courseCommunicationPriceHeader: "Inscríbete ahora",
    courseCommunicationPriceSubtext: "Pago único - Acceso de por vida",
    courseCommunicationCTA: "Comenzar Ahora",
    courseCommunicationFeature1: "Acceso ilimitado de por vida",
    courseCommunicationFeature2: "Disponible en todos tus dispositivos",
    courseCommunicationFeature3: "Certificado de finalización",
    courseCommunicationFeature4: "Soporte directo de Michelle",
    courseCommunicationGuaranteeTitle: "Garantía de 30 días",
    courseCommunicationGuaranteeText: "Si no estás satisfecha, te devolvemos tu dinero sin preguntas.",
    courseCommunicationStat1: "parejas ayudadas",
    courseCommunicationStat2: "valoración promedio",
    courseCommunicationStat3: "tasa de finalización",
    courseCommunicationTestimonialsTitle: "Lo que dicen nuestros estudiantes",
    courseCommunicationTestimonial1: "\"Aprendimos a comunicarnos sin herirnos. Ahora podemos hablar de cualquier tema sin miedo. Este curso salvó nuestra relación.\"",
    courseCommunicationTestimonial1Role: "Pareja, 10 años juntos",
    courseCommunicationTestimonial2: "\"Las técnicas de escucha activa cambiaron todo. Mi pareja por fin se siente escuchada y valorada.\"",
    courseCommunicationTestimonial2Role: "Terapia de pareja",
    courseCommunicationTestimonial3: "\"La comunicación no violenta transformó nuestras discusiones en conversaciones productivas. Gracias Michelle.\"",
    courseCommunicationTestimonial3Role: "Coaching de comunicación"
    });

    // Extender traducciones en inglés
    Object.assign(translations.en, {
    // CURSO AUTOESTIMA - SELF-ESTEEM
    courseSelfEsteemTitlePage: "Self-Esteem and Self-Love | Living in Love",
    courseSelfEsteemTitle: "Self-Esteem and Self-Love | Living in Love",
    courseSelfEsteemHeroTitle: "Self-Esteem and Self-Love: The Path to Your Best Version",
    courseSelfEsteemHeroSubtitle: "Rebuild your confidence, love yourself unconditionally, and create the life you deserve from self-love",
    courseSelfEsteemModules: "6 complete modules",
    courseSelfEsteemDuration: "4 intensive weeks",
    courseSelfEsteemAccess: "Lifetime access",
    courseSelfEsteemCertificate: "Certificate included",
    courseSelfEsteemWorkbook: "Downloadable workbook",
    courseSelfEsteemDescTitle: "About this course",
    courseSelfEsteemDesc1: "Do you feel trapped in patterns of constant self-criticism? Do you doubt your worth and allow others to cross your boundaries? It's time to transform your relationship with yourself and build unshakeable self-esteem that sustains you in every area of your life.",
    courseSelfEsteemDesc2: "In this 6-module program, you'll explore the roots of your self-esteem, identify self-destructive patterns, rebuild your self-image, and learn self-love practices that will transform your life. This is not just another motivational course: it's a deep process of healing and personal empowerment.",
    courseSelfEsteemBenefitsTitle: "What will you achieve?",
    courseSelfEsteemBenefit1: "Understand the psychological foundations of self-esteem and how to strengthen it",
    courseSelfEsteemBenefit2: "Identify and transform patterns of self-sabotage and self-criticism",
    courseSelfEsteemBenefit3: "Develop a positive and realistic self-image",
    courseSelfEsteemBenefit4: "Practice authentic self-love in your daily life",
    courseSelfEsteemBenefit5: "Create self-care routines that nourish your overall well-being",
    courseSelfEsteemBenefit6: "Keep your self-esteem elevated even in difficult times",
    courseSelfEsteemCurriculumTitle: "Course content",
    courseSelfEsteemModule1: "The Foundations of Self-Esteem",
    courseSelfEsteemModule1Duration: "4 lessons",
    courseSelfEsteemModule1L1: "What is self-esteem and why is it fundamental",
    courseSelfEsteemModule1L2: "The 4 pillars of healthy self-esteem",
    courseSelfEsteemModule1L3: "Personal assessment: Where is your self-esteem now?",
    courseSelfEsteemModule1L4: "Exercise: Your self-esteem map",
    courseSelfEsteemModule2: "Identifying Self-Destructive Patterns",
    courseSelfEsteemModule2Duration: "3 lessons",
    courseSelfEsteemModule2L1: "Recognizing negative inner dialogue",
    courseSelfEsteemModule2L2: "Most common self-sabotage patterns",
    courseSelfEsteemModule2L3: "Where your limiting beliefs come from",
    courseSelfEsteemModule3: "Rebuilding Your Self-Image",
    courseSelfEsteemModule3Duration: "4 lessons",
    courseSelfEsteemModule3L1: "Challenging limiting beliefs",
    courseSelfEsteemModule3L2: "Creating powerful affirmations that work",
    courseSelfEsteemModule3L3: "Mirror technique: Loving yourself",
    courseSelfEsteemModule3L4: "Celebrating your strengths and achievements",
    courseSelfEsteemModule4: "Self-Love in Practice",
    courseSelfEsteemModule4Duration: "3 lessons",
    courseSelfEsteemModule4L1: "What real self-love is (not selfishness)",
    courseSelfEsteemModule4L2: "Self-compassion: Treating yourself with kindness",
    courseSelfEsteemModule4L3: "Forgiving yourself",
    courseSelfEsteemModule5: "Integral Self-Care",
    courseSelfEsteemModule5Duration: "3 lessons",
    courseSelfEsteemModule5L1: "Creating your personalized self-care routine",
    courseSelfEsteemModule5L2: "Physical, emotional, and spiritual self-care",
    courseSelfEsteemModule5L3: "Saying NO without guilt",
    courseSelfEsteemModule6: "Keeping Your Self-Esteem High",
    courseSelfEsteemModule6Duration: "4 lessons",
    courseSelfEsteemModule6L1: "Protecting your self-esteem from external attacks",
    courseSelfEsteemModule6L2: "Surrounding yourself with people who uplift you",
    courseSelfEsteemModule6L3: "Long-term maintenance plan",
    courseSelfEsteemModule6L4: "Final celebration and commitment to yourself",
    courseSelfEsteemInstructorTitle: "Your instructor",
    courseSelfEsteemInstructorRole: "Self-Esteem Coach and Personal Development",
    courseSelfEsteemInstructorBio: "Michelle has helped over 800 women rebuild their self-esteem and discover their worth. Her approach combines positive psychology techniques, transformational coaching, and spiritual practices.",
    courseSelfEsteemPriceHeader: "Enroll now",
    courseSelfEsteemPriceSubtext: "One-time payment - Lifetime access",
    courseSelfEsteemCTA: "Start Now",
    courseSelfEsteemFeature1: "Unlimited lifetime access",
    courseSelfEsteemFeature2: "Available on all your devices",
    courseSelfEsteemFeature3: "Completion certificate",
    courseSelfEsteemFeature4: "Downloadable workbook with exercises",
    courseSelfEsteemGuaranteeTitle: "30-day guarantee",
    courseSelfEsteemGuaranteeText: "If you're not satisfied, we'll refund your money with no questions asked.",
    courseSelfEsteemStat1: "students transformed",
    courseSelfEsteemStat2: "average rating",
    courseSelfEsteemStat3: "completion rate",
    courseSelfEsteemTestimonialsTitle: "What our students say",
    courseSelfEsteemTestimonial1: "\"This course changed my life. I learned to truly love and respect myself. Today I feel secure and happy with myself.\"",
    courseSelfEsteemTestimonial1Role: "Personal development",
    courseSelfEsteemTestimonial2: "\"The self-compassion techniques were revolutionary. I stopped being my worst critic and became my best ally.\"",
    courseSelfEsteemTestimonial2Role: "Individual coaching",
    courseSelfEsteemTestimonial3: "\"I finally understood that I deserve love and respect. This course was the beginning of my true transformation.\"",
    courseSelfEsteemTestimonial3Role: "Online course",
    
    // CURSO COMUNICACIÓN - COMMUNICATION
    courseCommunicationTitlePage: "Couple Communication | Living in Love",
    courseCommunicationTitle: "Couple Communication | Living in Love",
    courseCommunicationHeroTitle: "Couple Communication: Deep Connection Through Words",
    courseCommunicationHeroSubtitle: "Master the art of effective communication and transform your relationships creating deep and lasting connections",
    courseCommunicationModules: "7 complete modules",
    courseCommunicationDuration: "5 weeks of transformation",
    courseCommunicationAccess: "Lifetime access",
    courseCommunicationCommunity: "Exclusive practice group",
    courseCommunicationCertificate: "Certificate included",
    courseCommunicationSupport: "Direct support from Michelle",
    courseCommunicationDescTitle: "About this course",
    courseCommunicationDesc1: "Do you feel unheard? Do arguments always end badly? This course will teach you to communicate effectively, empathetically, and transformatively in your relationship.",
    courseCommunicationDesc2: "Through 7 practical modules, you'll learn the most powerful techniques of nonviolent communication, active listening, and conflict resolution to create deep and lasting connections.",
    courseCommunicationBenefitsTitle: "What will you achieve?",
    courseCommunicationBenefit1: "Master nonviolent and empathetic communication",
    courseCommunicationBenefit2: "Express needs without attacking or hurting",
    courseCommunicationBenefit3: "Develop active and deep listening",
    courseCommunicationBenefit4: "Transform conflicts into growth opportunities",
    courseCommunicationBenefit5: "Interpret and use body language effectively",
    courseCommunicationBenefit6: "Create daily communication rituals with your partner",
    courseCommunicationBenefit7: "Create a personalized communication plan for your relationship",
    courseCommunicationCurriculumTitle: "Course content",
    courseCommunicationModule1: "Foundations of Effective Communication",
    courseCommunicationModule1Duration: "3 lessons",
    courseCommunicationModule1L1: "Why communication fails in couples",
    courseCommunicationModule1L2: "The 4 pillars of conscious communication",
    courseCommunicationModule1L3: "Assessment: How do you communicate now?",
    courseCommunicationModule2: "Communication Barriers",
    courseCommunicationModule2Duration: "4 lessons",
    courseCommunicationModule2L1: "The 4 horsemen of the apocalypse in communication",
    courseCommunicationModule2L2: "Criticism vs. complaint: The crucial difference",
    courseCommunicationModule2L3: "Defensiveness: How to overcome it",
    courseCommunicationModule2L4: "Exercise: Identifying your barriers",
    courseCommunicationModule3: "Active and Empathetic Listening",
    courseCommunicationModule3Duration: "3 lessons",
    courseCommunicationModule3L1: "What truly listening means",
    courseCommunicationModule3L2: "Emotional validation techniques",
    courseCommunicationModule3L3: "Practice: Deep listening exercises",
    courseCommunicationModule4: "Expressing Needs Without Attacking",
    courseCommunicationModule4Duration: "4 lessons",
    courseCommunicationModule4L1: "The nonviolent communication formula",
    courseCommunicationModule4L2: "Using 'I' messages instead of 'You'",
    courseCommunicationModule4L3: "Expressing emotions without blaming",
    courseCommunicationModule4L4: "Exercise: Rewriting difficult conversations",
    courseCommunicationModule5: "Body Language and Non-Verbal Communication",
    courseCommunicationModule5Duration: "3 lessons",
    courseCommunicationModule5L1: "The 93% that aren't words",
    courseCommunicationModule5L2: "Reading your partner's body language",
    courseCommunicationModule5L3: "Aligning your verbal and non-verbal communication",
    courseCommunicationModule6: "Managing Difficult Conversations",
    courseCommunicationModule6Duration: "3 lessons",
    courseCommunicationModule6L1: "Preparing for difficult conversations",
    courseCommunicationModule6L2: "Conscious time-out technique",
    courseCommunicationModule6L3: "Reaching win-win agreements",
    courseCommunicationModule7: "Communication Plan for Couples",
    courseCommunicationModule7Duration: "3 lessons",
    courseCommunicationModule7L1: "Creating daily communication rituals",
    courseCommunicationModule7L2: "Couple meetings: How and when",
    courseCommunicationModule7L3: "Your personalized action plan",
    courseCommunicationInstructorTitle: "Your instructor",
    courseCommunicationInstructorRole: "Couples Therapist and Communication Expert",
    courseCommunicationInstructorBio: "Michelle has facilitated over 5,000 couple therapy sessions, specializing in effective communication. Her method has helped hundreds of couples reconnect and strengthen their love.",
    courseCommunicationPriceHeader: "Enroll now",
    courseCommunicationPriceSubtext: "One-time payment - Lifetime access",
    courseCommunicationCTA: "Start Now",
    courseCommunicationFeature1: "Unlimited lifetime access",
    courseCommunicationFeature2: "Available on all your devices",
    courseCommunicationFeature3: "Completion certificate",
    courseCommunicationFeature4: "Direct support from Michelle",
    courseCommunicationGuaranteeTitle: "30-day guarantee",
    courseCommunicationGuaranteeText: "If you're not satisfied, we'll refund your money with no questions asked.",
    courseCommunicationStat1: "couples helped",
    courseCommunicationStat2: "average rating",
    courseCommunicationStat3: "completion rate",
    courseCommunicationTestimonialsTitle: "What our students say",
    courseCommunicationTestimonial1: "\"We learned to communicate without hurting each other. Now we can talk about any topic without fear. This course saved our relationship.\"",
    courseCommunicationTestimonial1Role: "Couple, 10 years together",
    courseCommunicationTestimonial2: "\"The active listening techniques changed everything. My partner finally feels heard and valued.\"",
    courseCommunicationTestimonial2Role: "Couple therapy",
    courseCommunicationTestimonial3: "\"Nonviolent communication transformed our arguments into productive conversations. Thank you Michelle.\"",
    courseCommunicationTestimonial3Role: "Communication coaching"
    });
    
    console.log('Traducciones de cursos extendidas correctamente');
} else {
    console.error('El objeto translations no está disponible');
}
